spring:
  application:
    name: todoSchemeBackend

  config:
    import: optional:file:.env[.properties]

  devtools:
    restart:
      enabled: false

server:
  port: 8080
  compression.enabled: true
  http2.enabled: true

kind: Application

logging:
  level:
    org:
      springframework:
        boot:
          devtools:
            restart: OFF

#hibernate.transaction.jta.platform: